spring.application.name=spring-ai-prompt-engineering
#spring.ai.openai.api-key=${OPENAI_API_KEY}

# spring.ai.openai.chat.options.model=gpt-4

spring.ai.ollama.chat.options.model=llama3.2
# 1. Enforce strict JSON object output mode
#spring.ai.ollama.chat.options.format=json
# 2. Lower the temperature so the model follows instructions rigidly instead of hallucinating schema files
spring.ai.ollama.chat.options.temperature=0.1
